### ISSUE TITLE
x86-windows-static-* files actually use VCPKG_TARGET_ARCHITECTURE x64

### ISSUE THREAD

**Issue by mr-tz** [williballenthin/siglib#14]
The architecture should be set to `x86`.

See for example
https://github.com/williballenthin/siglib/blob/5611c7a63908e97a884c6dfcaf6ed2ddc62b9411/x86-windows-static-v142.cmake#L1

**Comment by williballenthin** [comment]
wow good catch

**Comment by williballenthin** [comment]
i wonder if i had made the changes locally in my docker container or something
