### ISSUE TITLE
flirt: compare sig coverage

### ISSUE THREAD

**Issue by mr-tz** [williballenthin/siglib#17]
for example this sig file covers x% of `vc32rtf`

**Comment by williballenthin** [comment]
here is a release build of lancelot/match_flirt for 64-bit linux (ubuntu 20.04). it performs just as well as the viv-utils implementation (to the degree that they recognize the same functions) yet since its native code, is much faster:

```
> time match_flirt vc32rtf.sig 034b7231a49387604e81a5a5d2fe7e08f6982c418a28b719d2faace3c312ebb5.exe_
2021-03-23 09:43:08 [INFO ]  found 320 functions
0x404a80: (public) __alloca_probe
0x404a8c: (local)  probepages
...
0x40cae1: (public) __getdcwd_lk
0x40cbb6: (public) __validdrive
../target/release/match_flirt ~/code/capa-pub/sigs/vc32rtf.sig   0.56s user 0.02s system 99% cpu 0.583 total
```

this may be helpful when running our coverage tests against a bunch of files.

[match_flirt.zip](https://github.com/williballenthin/siglib/files/6190901/match_flirt.zip)

**Comment by mr-tz** [comment]
This is great. Runs super fast!

I ran vc32rtf (left) vs. an `all.sig` (right) I created and compared the output using meld.  Observations:

# Overall results look very similar!

# Often my sig doesn't give us the name, but we know it's a library function
likely can be improved by exploring the .exc file?

![2021-03-25_14-06-42](https://user-images.githubusercontent.com/17606537/112477537-69294580-8d73-11eb-9be7-1542cafb0d1e.png)

![2021-03-25_14-10-50](https://user-images.githubusercontent.com/17606537/112478113-f2d91300-8d73-11eb-80f3-58732465e839.png)


# vs32rtf may filter out $LN* (local name", data ref", ???)
likely via sigmake option/directive DATA=name?

![2021-03-25_13-49-59](https://user-images.githubusercontent.com/17606537/112475632-5150c200-8d71-11eb-8db6-822afb4151f9.png)

# same with label*?
![2021-03-25_14-09-23](https://user-images.githubusercontent.com/17606537/112477922-be655700-8d73-11eb-8496-e2c3887468ca.png)

**Comment by mr-tz** [comment]
![2021-03-25_14-13-46](https://user-images.githubusercontent.com/17606537/112478486-5a8f5e00-8d74-11eb-8439-0d3a7223b072.png)

these "unrecognized" functions are defined in other sig files (I only ran vc32rtf), see below

![2021-03-25_14-14-06](https://user-images.githubusercontent.com/17606537/112478522-62e79900-8d74-11eb-8ef7-fb24234c8dce.png)

Can you modify match_flirt to load multiple sig files?

**Comment by mr-tz** [comment]
`LN*` seems to be mostly used for relocation types `IMAGE_REL_I386_SECTION`, and `IMAGE_REL_I386_SECREL`. The locations often line up with the starts of basic blocks and do not identify/name functions.

**Comment by williballenthin** [comment]
> Can you modify match_flirt to load multiple sig files?

sure, i'll do this right now

**Comment by williballenthin** [comment]
[match_flirt.zip](https://github.com/williballenthin/siglib/files/6205606/match_flirt.zip)

now exe comes first, sigs come second:

```
USAGE:
    match_flirt [FLAGS] <input> <sig>...

FLAGS:
    -h, --help       Prints help information
    -q, --quiet      disable informational messages
    -V, --version    Prints version information
    -v, --verbose    log verbose messages

ARGS:
    <input>     path to file to analyze
    <sig>...    path to FLIRT sig/pat
```

**Comment by mr-tz** [comment]
```
$ ./match_flirt Practical\ Malware\ Analysis\ Lab\ 01-01.dll_ sigs/ida/vc32mfce.sig
2021-03-25 09:05:22 [ERROR]  The sig file compression method is not supported: unknown ZLIB method CM=0xc
```

not sure if it's me, but this is a sig from IDA 7.5.

**Comment by mr-tz** [comment]
[diff.txt](https://github.com/williballenthin/siglib/files/6206494/diff.txt)

IDA sigs on the left, my sig `all.sig` on the right.

```
0x404b30: (public) _strcpy				      |	0x404b30: (public) ?
0x404b40: (public) _strcat				      |	0x404b40: (public) ?
0x404b4d: (local)  dest_misaligned			      <
0x404b5c: (local)  find_end_of_dest_string_loop		      <
0x404b8f: (local)  start_byte_3				      <
0x404b94: (local)  start_byte_2				      <
0x404b99: (local)  start_byte_1				      <
0x404b9e: (local)  start_byte_0				      <
0x404ba1: (local)  copy_start				      <
0x404bad: (local)  src_misaligned			      <
0x404bc1: (local)  main_loop				      <
0x404bc6: (local)  main_loop_entrance			      <
0x404bfa: (local)  byte_3				      <
0x404c02: (local)  byte_2				      <
0x404c0f: (local)  byte_1				      <
0x404c18: (local)  byte_0				      <
							      >	0x404d98: (public) _free
0x405022: (public) __dosmaperr				      |	0x404f26: (public) __heap_alloc
0x405153: (public) _fread				      |	0x405153: (public) ?
0x4054a6: (public) _fwrite				      |	0x4054a6: (public) ?
0x4055b0: (public) _memcpy				      |	0x4055b0: (public) ?
0x405620: (local)  LeadUp1				      |	0x405620: (local)  ?
0x40564c: (local)  LeadUp2				      |	0x40564c: (local)  ?
0x405670: (local)  LeadUp3				      |	0x405670: (local)  ?
0x4056ac: (local)  UnwindUp7				      |	0x4056ac: (local)  ?
0x4056b4: (local)  UnwindUp6				      |	0x4056b4: (local)  ?
0x4056bc: (local)  UnwindUp5				      |	0x4056bc: (local)  ?
0x4056c4: (local)  UnwindUp4				      |	0x4056c4: (local)  ?
0x4056cc: (local)  UnwindUp3				      |	0x4056cc: (local)  ?
0x4056d4: (local)  UnwindUp2				      |	0x4056d4: (local)  ?
0x4056dc: (local)  UnwindUp1				      |	0x4056dc: (local)  ?
0x4056ef: (local)  UnwindUp0				      |	0x4056ef: (local)  ?
0x405708: (local)  TrailUp0				      |	0x405708: (local)  ?
0x405710: (local)  TrailUp1				      |	0x405710: (local)  ?
0x40571c: (local)  TrailUp2				      |	0x40571c: (local)  ?
0x405730: (local)  TrailUp3				      |	0x405730: (local)  ?
0x4057a8: (local)  LeadDown1				      |	0x4057a8: (local)  ?
0x4057c8: (local)  LeadDown2				      |	0x4057c8: (local)  ?
0x4057f0: (local)  LeadDown3				      |	0x4057f0: (local)  ?
0x405844: (local)  UnwindDown7				      |	0x405844: (local)  ?
0x40584c: (local)  UnwindDown6				      |	0x40584c: (local)  ?
0x405854: (local)  UnwindDown5				      |	0x405854: (local)  ?
0x40585c: (local)  UnwindDown4				      |	0x40585c: (local)  ?
0x405864: (local)  UnwindDown3				      |	0x405864: (local)  ?
0x40586c: (local)  UnwindDown2				      |	0x40586c: (local)  ?
0x405874: (local)  UnwindDown1				      |	0x405874: (local)  ?
0x405887: (local)  UnwindDown0				      |	0x405887: (local)  ?
0x4058a0: (local)  TrailDown0				      |	0x4058a0: (local)  ?
0x4058a8: (local)  TrailDown1				      |	0x4058a8: (local)  ?
0x4058b8: (local)  TrailDown2				      |	0x4058b8: (local)  ?
...
```

**Comment by mr-tz** [comment]
The `-lr` argument for sigmake allows to filter out functions/labels by name. Can be used multiple times, like:
```
sigmake -lr $LN -lr label ...
```
