### ISSUE TITLE
add VS6 compiler

### ISSUE THREAD

**Issue by williballenthin** [williballenthin/siglib#2]
this is what was used to compile PMA.

at least extract the c/c++ runtimes from this compiler. probably can't use vcpkg with this, though.

**Comment by williballenthin** [comment]
- https://www.codeproject.com/Articles/1191047/Install-Visual-Studio-on-Windows
  - http://nuke.vbcorner.net/Articles/VB60/VisualStudio6Installer/tabid/93/language/en-US/Default.aspx
  - https://stackoverflow.com/a/31981700/87207

**Comment by williballenthin** [comment]
## results

C/C++ runtime .lib MD5 hashes and link to .pat files:

|  lib | md5 | .pat link |
|-|-|-|
|msvcrt.lib|abcdef|http://...|

**Comment by mr-tz** [comment]
Service Pack 6 for Visual Basic 6.0, Visual C++ 6.0 with Visual Source Safe 6.0d
http://www.microsoft.com/en-us/download/details.aspx?id=9183 via https://stackoverflow.com/a/31981700/10548020

see `VS6sp61\vc98\lib` for the runtime / standard libraries
