### ISSUE TITLE
Remove sigs that are too general

### ISSUE THREAD

**Issue by mr-tz** [williballenthin/siglib#6]
For example
```
FF25............................................................ 00 0000 0006 :0000 _BSTR_UserFree@8 ^0002 BSTR_UserFree 
FF25............................................................ 00 0000 0006 :0000 _BSTR_UserMarshal@12 ^0002 BSTR_UserMarshal 
...
```

`pcf` supports the `-M##` option to increase the min number of defined bytes.

Can we identify other patterns that likely will FP?

**Comment by williballenthin** [comment]
does the above FP often? this looks like a signature for a wrapper function, which requires the reference name to match, and that could be pretty complex.

**Comment by williballenthin** [comment]
good call on `-M##`, i hadn't read that closely yet.

**Comment by mr-tz** [comment]
hm yeah, I just thought intuitively, how useful can this be?

disassembles to a jmp
`ff 25 00 00 00 00       jmp    DWORD PTR ds:0x0 `

**Comment by mr-tz** [comment]
never mind, seems to be useful for recursive flirt matching
